global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor pour les métriques des conteneurs
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node.js application
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:3000']
    metrics_path: /metrics
    scrape_interval: 10s

  # Python application
  - job_name: 'python-app'
    static_configs:
      - targets: ['python-app:5000']
    metrics_path: /metrics
    scrape_interval: 10s

  # Go application
  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # PostgreSQL (si exporter disponible)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis (si exporter disponible)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 10s